### ISSUE TITLE
土壌硬度データからのヒストグラム生成

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#21]
土壌硬度データから計算された特性深度をヒストグラムに変換してグラフ表示

**Comment by duri0214** [comment]
@yoshiyukiminami プログラム言語には得手不得手があることがあります。
- excelはヒストグラムを出そうとするといくつかのステップを踏まなければならず、セルが移動してしまうと壊れる可能性がある
- pythonはデータを「食わせて」コマンド一発で度数分布を配列で返してくれる

などです。お互いの得意な部分を組み合わせてカンタンに作れないか考えることは価値のあることです。例えば以下のように

- データは excel にある（csvを集めて読んでシートに展開するなどの機能も含めて）
- pythonでexcelシートの生データを読み、度数分布を出したらdbに保存
- excelでvbaのボタンを押すとdbから度数分布を読み込みグラフに展開する

**Comment by duri0214** [comment]
これも終わりかどうか明日確認

**Comment by yoshiyukiminami** [comment]
ヒストグラム生成のプログラムは一旦完了
