### ISSUE TITLE
データのトリミング-無効データ判定

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#26]
測定方法の問題で測定したデータに無効なデータが混入していることを判定し、エラー表示を出すコマンドの作成
・土壌深度1㎝～60㎝（データは1㎝間隔で取得）のうち10㎝～55㎝の範囲で232キロパスカルの最低値データが複数回出現する
→エラー表示「このデータは無効なデータ値が含まれています」
[data_sample_error-disp-on.csv](https://github.com/yoshiyukiminami/python/files/8674097/data_sample_error-disp-on.csv)

**Comment by yoshiyukiminami** [comment]
処理として考えられるのは、土壌深度1㎝～60㎝（10㎝～50㎝と範囲を限定しても可）の値をチェックし、232という数値が複数出ているデータ行を検知する。

∔補正は可能か・・例：｛・・20㎝,21cm,22cm,23cm,24cm・・:・・500,600,_232_,_232_,900・・｝→｛・・20㎝,21cm,22cm,23cm,24cm・・:・・500,600,**700**,**800**,900・・｝

**Comment by duri0214** [comment]
@yoshiyukiminami この issue 終わってるなら閉じましょう
