### ISSUE TITLE
調査｜plotlyの画像保存がうまくいかない

### ISSUE THREAD

**Issue by duri0214** [yoshiyukiminami/python#30]
`data_prepro_temp1` ブランチの `data_processing/tekusei_stats_cal.py` 内において、 `write_image` がフリーズするため調査

https://github.com/yoshiyukiminami/python/blob/data_prepro_temp1/data_processing/tekusei_stats_cal.py#L184

**Comment by duri0214** [comment]
@yoshiyukiminami 読み込むCSVがないっぽいので、ダミーデータでグラフを作って `write_image` が通るかってとこだけとりあえず見ますね

**Comment by duri0214** [comment]
![image](https://user-images.githubusercontent.com/19668980/175761221-34e10e09-9115-4dce-b850-6f16c7ac6c2b.png)
シンプルなサンプルだとすんなり保存できるので、ライブラリの問題というよりはCSVからグラフを作る間になにか原因がありそう

**Comment by duri0214** [comment]
https://github.com/plotly/Kaleido/issues/80

@yoshiyukiminami このログだしやってみましょう。まともなの出てこなかったらライブラリの変更も視野にいれましょう（やっぱり僕の環境だと動くし、そもそも拡大縮小が必要なのか？という点も含めて）
https://github.com/plotly/Kaleido/issues/36#issuecomment-756676527

```python
import plotly.io as pio
scope = pio.kaleido.scope
print(scope._std_error.getvalue().decode())
```

**Comment by yoshiyukiminami** [comment]
ライブラリーを変更して解決
