### ISSUE TITLE
土壌硬度データのグラフ化（VBA→python）

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#31]
以前に作成した土壌硬度データのグラフ化マクロをpythonでRE作成
その際、以下の点を改良
　・読み込みできるファイルを同時・複数できるようにする
　・作成したグラフ画像の自動保存（ファイル名の自動生成、特定パスの選択、画像サイズなどプロパティ設定）

追伸：excelマクロファイルは添付できないようなので、メッセンジャーで別途共有します

**Comment by duri0214** [comment]
圧縮ファイルの状態にすると貼り付けることができます
[土壌硬度データ_グラフ自動変換マクロ_basic_ver2.2.zip](https://github.com/yoshiyukiminami/python/files/8985983/_._basic_ver2.2.zip)

**Comment by yoshiyukiminami** [comment]
一通り、土壌硬度データから分布グラフ（折れ線グラフ）生成するプログラムはできたのですが、相変わらずwrite_imageが動かないですね。
動作は、確認済みです。

**Comment by yoshiyukiminami** [comment]
グラフ生成で残っていたパラメータ間の散布グラフを4種類追加しました。
残った課題は、グラフ画像の自動保存と土壌硬度分布の計算データをdict型のAll_listに格納する2点になります。

**Comment by duri0214** [comment]
@yoshiyukiminami `write_image` まで行けないんですよね。。
リファクタリングしたほうがいいんだろうか。。
でもexcelのデータが悪いような気もする

![image](https://user-images.githubusercontent.com/19668980/177320597-655bed6d-6276-4656-9ff6-f3004564524d.png)

`xC` ってキーがないぞ　って言われてるんですが `xC` ってexcelにある列でしたっけ？
![image](https://user-images.githubusercontent.com/19668980/177321009-8729d43d-732b-41a1-9f09-3694f3700471.png)

**Comment by yoshiyukiminami** [comment]
複数農場名、圃場名での確認済み

**Comment by yoshiyukiminami** [comment]
VBAサンプルデータのヘッダーが今やっているpythonのデータと齟齬がありました。パラメータの名前が違っています。
パラメータDがxCになります。
[basic_header_format.csv](https://github.com/yoshiyukiminami/python/files/9050209/basic_header_format.csv)

**Comment by duri0214** [comment]
@yoshiyukiminami 
そしたらエクセルマクロのほうを直してgithubにあげなおしてもらうか、読み込む想定のcsvをあげといてください

**Comment by yoshiyukiminami** [comment]
こちらのcsvを使ってください。
[data_sample_hp-1.csv](https://github.com/yoshiyukiminami/python/files/9053263/data_sample_hp-1.csv)

**Comment by duri0214** [comment]
@yoshiyukiminami 

わかりました。使っちゃいけない文字（スラッシュ）使ってます。なんでもいいんでスラッシュつけてファイル保存しようとしてみてください。windowsから怒られるはずです。
- どんな文字でファイル名を作ろうとしているか
- 作ったパスをwindowsのエクスプローラで開けるか
の点検が必要です
![image](https://user-images.githubusercontent.com/19668980/177546273-e4944589-7772-45cf-99ca-ac44b9a14104.png)
![image](https://user-images.githubusercontent.com/19668980/177546327-5958d593-f236-4bf2-a6bd-8dbf2e0485ee.png)
![image](https://user-images.githubusercontent.com/19668980/177546641-5adbf8c6-a71b-426b-8e1f-c2ca0c95ea2f.png)

**Comment by yoshiyukiminami** [comment]
#32 に統合
