### ISSUE TITLE
土壌化学性データの読み込みとグラフ化

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#36]
測定データの読み込みと土壌化学性データからグラフ化するプログラム

**Comment by yoshiyukiminami** [comment]
グラフのイメージ
横棒グラフ
X軸：各項目の数値→基準値で割ったパーセント表示
Y軸：各項目・・畑毎に複数項目
色わけ①：100％以上＝それ以上の投入を控えるべき項目は赤
色わけ②：○％以下＝投入すべき項目は青
色わけ③：①②以外はグレー
グラフの種類は「窒素関連」「リン酸関連」「塩基関連」「土壌ポテンシャル関連」の4種類
「窒素関連」項目：EC、可給態NH4、可給態NO3、無機態窒素、NH4/NO3
「リン酸関連」項目：交換性P、P吸収
「塩基関連」項目：PH、交換性Ca、交換性Mg、交換性K、塩基飽和度、Ca/Mg、Mg/K
「土壌ポテンシャル関連」項目：CEC、腐食、仮比重、P係数
<img width="824" alt="Whiteboard 2 -01" src="https://user-images.githubusercontent.com/96449875/181903678-28b7d8d0-f9ce-49bb-bfff-d6b8a27de97e.png">

**Comment by duri0214** [comment]
@yoshiyukiminami 
最低限必要なグラフの機能
- 積み上げグラフ（...ないものを探すほうが難しいけど）

なぜ必要かというと、このピンクの四角の部分（基準値と実測値の差）をグラフ化して乗っけるためです
![image](https://user-images.githubusercontent.com/19668980/181905640-634e6adf-6e69-4707-8f9b-75c782eae04e.png)
