### ISSUE TITLE
python-practice

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#4]

**Comment by duri0214** [comment]
@yoshiyukiminami お、ここを使おうとするのは素晴らしいですね。ここはissue（起票）機能です。ビジネスサイド（運用のひととか）が、やれバグが出たから直してほしい、とか改修要望を書いたりします。

そして開発側のマネージャーが定期的に、川のように流れてきたissueを捌く感じですね。

いまの南さんからだと、次に何をするのかというのを（１週間くらいで終わるような粒度で）バリバリと書き込んでいくのがいいと思います。

**Comment by yoshiyukiminami** [comment]
@duri0214 何もわからないままスマホでGithub使えるようにした中で設定しました。
このissueはそういう使い方するんですね。
