### ISSUE TITLE
画像から自動的に画像情報を取得し、画像処理（サイズ縮小）・ファイル名を付けて保存

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#53]
1. スマホやタブレットで撮影された圃場画像を取得
2. 画像から画像情報（GPS、撮影日時）を取得
3. 測定データの基本情報から、GPS情報に合致する「圃場名」「ID」を取得
4. 1と2から画像の「圃場名」「ID」を特定
5. 画像のファイル名を変更・・圃場画像_ID（年4桁_生産者No.5桁_測定No.5桁）_圃場名_分類（left、right、center、otherの4種）_撮影日（年4桁∔月2桁∔日2桁）.jpeg
6. 画像の保存サイズを533×400に縮小
7. 所定フォルダに保存

検討事項
1. 圃場名の分類を撮影現場の入力手間を省くため、複数ある場合は単純に1からの連番を振り分ける？
2. 同じ圃場でIDが複数ある場合の特定方法は？
3. エラー表示：①GPS情報がない（カメラ設定）、②GPS情報と一致する圃場名・IDがない、③GPS情報と一致する圃場名が複数ある・・②、③はGPS情報と比較する基本情報のGPSとの誤差をどの程度の範囲に設定するか？もしくは基本情報のGPSを必ず撮影する可能性が高い場所の緯度経度にする（現在、基本情報にはGoogleMapの航空写真で圃場の中心付近の緯度経度を入力。ただし変形圃場など複数地点で撮影する場合の対処が必要）
![基本情報GPS例](https://user-images.githubusercontent.com/96449875/210189672-ec52819f-d038-48b8-8c7c-6628c6fb59f3.jpg)

**Comment by yoshiyukiminami** [comment]
検討事項の3
変形圃場（L字など）や合筆等で巨大になった圃場など撮影場所が複数出てくる場合の対処をどうするか？

下記画像は同じ圃場を撮影したもので1枚目と2枚目では撮影場所が異なるケース
画像から取得した座標情報をGoogleMapで表示したものを追加添付

![IMG_9876](https://user-images.githubusercontent.com/96449875/210190922-cde6301e-10b9-451b-9e51-72e50006274e.jpeg)
![1枚目画像の座標（同一圃場・L字変形）](https://user-images.githubusercontent.com/96449875/210190930-e88fd095-b922-4c5b-8f4f-19b1ae80e412.jpg)
![IMG_9877](https://user-images.githubusercontent.com/96449875/210190938-e1113ac0-3a3e-44fa-b76a-ce0410de62cf.jpeg)
![2枚目画像の座標（同一圃場・L字変形）](https://user-images.githubusercontent.com/96449875/210190942-d55679c6-57c7-408c-b5b5-b6cf564f30cc.jpg)

**Comment by duri0214** [comment]
（感想程度の雑メモ）
- 粒度メモ：顧客ID、圃場ID、ポジションID
- 写真はｎ枚ある
  - 「圃場名」「ID」を特定（「ID」とは顧客IDか？圃場IDか？）
  - リサイズ（533×400）
  - 所定フォルダに保存
- 測定した情報がExcelにまとまっている
  - 「圃場名」「ID」を特定（「ID」とは顧客IDか？圃場IDか？）

どこの作業を削りたくてユーザーの登録作業としてどこまでの作業を受け入れられるか。すべてを自動的にやってくれるサービスはないし、なにごとも特化すれば変化には弱くなる。
	・画像のアップロードに関して、（GPSから）いつどこの圃場のどのポジションを何枚撮った、というのを自動判定は難しいと思うUIの工夫で乗り切ったほうがよさそう

それでも工夫するなら例えば
	・スマホやタブレットを圃場の数だけ準備する（→予算的に難しそう）
	・撮影するポジションの順番を決める
	・撮影時刻と撮影スケジュールで判定する
	・写真撮影時または撮影後に特定のフォルダにしまってもらう（→アップロード作業してもらうのとそれほど労力はかわらない）

検討事項３については、そもそも写真管理が、pptのレイアウトから定めているために１ポジション１写真という制約がつく。
面積が合体した圃場のポジション管理については、（ポジションあたりの面積が倍なる、など）単に解釈の問題だけども１ポジションｎ枚になることに対応するのであれば、「pptのレイアウトをもとに取り扱う写真の枚数を決めた」というプログラムの前提となる仕様を変更したほうがよさそう

**Comment by yoshiyukiminami** [comment]
IDは測定IDになります。測定ごとにユニークIDを振り分けており、同じ顧客（生産者）、同じ圃場でも測定したタイミングが違うとIDは別になります。

PPTX報告書での対応ステージでは、「画像の撮影」から報告書自動作成.pyに読み込ませるまでの「画像に読み込ませるときに必要な情報を紐付ける」「画像サイズを縮小する」業務効率化が目的なので、撮影するであろう場所の座標をあらかじめ圃場座標にするのがよさそうです。→逆に測定作業を依頼するときにここから撮影するという指示も同時にできる。問題は指定場所と実際の撮影場所とのズレが必ず起こるのを自動判定できるか？

**Comment by yoshiyukiminami** [comment]
撮影場所の自動判定は、とりあえず以下のように対応しました。
・圃場の座標情報を撮影場所と想定できる場所で登録する。
・想定した撮影場所以外で撮影した画像は、自動判定できない場合、renameで測定IDが「0000-00000-00000」「圃場名不明」と設定→後で手修正
・画像の種類として設定している「all」「left」「right」「other」については、仮番号（処理した順に０～）をrenameで付加し、後で手修正
