### ISSUE TITLE
気象庁の気象データから解析チャートを作成するためプログラム

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#54]
構成は下記の通り

1. 気象庁HPより測定地点別・過去気象データの取得・・アナログ対応
2. 取得したデータ（csv）を所定のdataframeに格納・・climate_data_dataframe.py
3. dataframeから任意期間のチャートを作成・・climate_data_analysis_chart.py

1. 観測地点1つ×7年期間×6項目（平均気温、日照時間、最高気温、最低気温、降水量の合計、1時間降水量の最大）データ（csv）をあらかじめDLし、所定のフォルダに格納・・観測地点当たり①2023年1月1日～本日、②2018～2022年、③2013～2017年、④2008～2012年
2. ①観測地点を紐付けと番号付け（※）、②年月日でソート、③データ無の補正（前後数値で補正値を代入）④【課題】うるう年をどうするか？　※チャート比較で年をまたぐ期間の選択があるため
3. ①基本の凡例は3つ本年、昨年、2018～2020年の3年平均（暖冬シーズン）、2011～2020年の10年平均

**Comment by yoshiyukiminami** [comment]
＜グラフ化プログラムの作成プロセス＞
# step-1:比較する期間の開始日と終了日を設定する
# step-2:各年度の開始日と終了日にあたる行番号を特定し、各年度の対象データを抽出する
# step-3:各年度の抽出データから項目毎のdataframeを作成する
# step-4:比較年度の項目毎dataframeをまとめる
# step-5:平均気温、日照時間は積算演算したdataframeを作成する
# step-6:各dataframeから本年度（2022）、昨年度（2021）、2018～2020年平均（暖冬3年）、2008～2020年平均を抽出、グラフ化の元dataframeを作成する
# step-7:グラフ化元dataframeから比較グラフを作成する

**Comment by duri0214** [comment]
@yoshiyukiminami step1-7のメモをもとに親子関係をもったissueを作成しました。こんな感じで子供のissueをまとめて管理することができます（よくわからないと思うので次回のzoomで説明します）
![image](https://user-images.githubusercontent.com/19668980/216760430-318ea22d-feb4-467f-a6f1-545eb85ed5b5.png)

**Comment by duri0214** [comment]
issue 3件の完了を確認済み
