### ISSUE TITLE
dfからある期間を抽出する関数の作成

### ISSUE THREAD

**Issue by duri0214** [yoshiyukiminami/python#57]
- step-1:比較する期間の開始日と終了日を設定する
  - 引数として取り込む `func_filtered_df(df, date_col_name, start_mmdd, end_mmdd)`
  - 引数 `df` はcsvパスでもいいかもしれない
- step-2:各年度の開始日と終了日にあたる行番号を特定し、各年度の対象データを抽出する
  - dfの日付列の値はCSVベースとなっており、「日付のフォーマットをもったテキスト」の前提なので、`date_col_name` の seriesをdatetime型に変換する
  - 日付で行フィルタした df を return する

9月から2月、のような年マタギを考慮する

**Comment by duri0214** [comment]
@yoshiyukiminami 
ソースコード取り込み済みだと思うのでブランチごと削除しますね

**Comment by yoshiyukiminami** [comment]
はい、ありがとうございます。
期間の考え方を取り入れて、最初の期間設定を「開始日（これは同じ）」と「期間（月」に変更して、開始日から5か月というような設定に変更しました。

**Comment by duri0214** [comment]
@yoshiyukiminami 
（取り入れるかはおまかせします）
- 「開始日から何ヶ月」といった指定の仕方にすると、積算温度という考え方からして、あまりあてにならない数字になりそう（9/20-2/1に収穫まで完了したときに2月末（2/20?）までの積算温度が出てしまう）
- 開始日、終了日は毎年それぞれ農業者によっても変わってくるので、結局「開始日・終了日」シートを作って蓄積するほうがよさそう（一度入れれば便利になるタイプ）
- たしか「{loop_year}-{kaishi.month}-{kaishi.day}」のような文字を作ってdatetimeに変換していましたが、ゴリゴリにループで日付操作するなら、単に datetime の初期化のかたちを使ったほうがシンプル
  ```python
  import datetime
  my_birth_day = datetime.date(2022, 4, 1)
  ```
