### ISSUE TITLE
大量の圃場を管理するWebアプリ

### ISSUE THREAD

**Issue by yoshiyukiminami** [yoshiyukiminami/python#7]
大量の圃場を以下の項目ごとにデータを紐付ける管理アプリ
＜項目＞
・圃場名
・栽培者/団体名（個人はなし）
・地域（県/市/町/村）
・栽培作物
・栽培年度
＜データ＞
・圃場住所
・面積
・マップコードまたは[筆ポリゴンID](https://www.maff.go.jp/j/tokei/porigon/)
・土壌硬度データ
・土壌化ガ性分析結果
・施肥量の削減目安（上記の土壌硬度データと土壌化学性分析結果から算出・・ここが弊社のノウハウになってきます）
・施肥設計
・施肥実績
・収量実績

**Comment by duri0214** [comment]
@yoshiyukiminami 応用問題のブランチはこのissueに紐づけます。
データベースの項目の型が、文字か日付かといった決めはいったんは僕の提案をここにまとめておく予定。

**Comment by duri0214** [comment]
- 圃場名
- 栽培者/団体名（個人はなし）
- 地域（県/市/町/村）　← @yoshiyukiminami 地域がn個発生する可能性はありますか？（ないとは思っている）
- 圃場住所　←TODO: 複数あるならテーブル作成の必要あり
- 栽培作物
- 栽培年度
- 面積
- マップコードまたは筆ポリゴンID
```python
class Hojou(models.Model):
    name = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)  # n個発生する可能性はあるのか？
    prefecture = models.CharField(max_length=50)  # n個発生する可能性はあるのか？
    area = models.FloatField(default=0, null=True)  # 面積ってもっとわかりやすい単語はないのか
    map_code = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

class Item(models.Model):
    name = models.CharField(max_length=50)
    beginning_year = models.CharField(max_length=50)  # 年度まででいいのか？
    hojou = models.ForeignKey(Hojou, verbose_name='圃場名', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)
```

＜データ＞　あとは南さんに聞かないとなんともいえないな...
・土壌硬度データ
・土壌化ガ性分析結果
・施肥量の削減目安（上記の土壌硬度データと土壌化学性分析結果から算出・・ここが弊社のノウハウになってきます）
・施肥設計
・施肥実績
・収量実績

**Comment by yoshiyukiminami** [comment]
上記のプッシュは「#8」の紐付けにしないといけなかったですね。
past_data_scrapingを2002年1月の菊川牧之原地区データのみ自動収集してDbeaverの「sample_1_temperature」に取り込むテストしていますが、dataflameの設定でとん挫している感じです。追加した列の「pref_no」「chiku_no」の構文かmodels.pyのデータフレーム設定、またはmodels.pyと連携するための何かに不具合がありそうですが・・
![past_data_scraping_error1](https://user-images.githubusercontent.com/96449875/151947350-6de5598f-7069-43f6-a9b7-f3b7ddda0c19.jpg)

**Comment by duri0214** [comment]
@yoshiyukiminami ちょっと現在の変更箇所がわかんないのでプルリク発行してください
`sample_1` ってなんだっけ...　→あ、アプリ名か。思い出し用にプルリクに諸情報（プロジェクト名、アプリ名、使用する予定のデータベーステーブルなど、南さんも思い出しが効くような情報）も書いといてください

あとデータフレームの設定のなにでつっかえているのか
- エラーが出ているのか
- 意図した結果にならないのか

など、テキストで質問するところも重要です（整理してテキストで伝えるって実は難易度高いんです）

**Comment by yoshiyukiminami** [comment]
一旦、このissueはクローズ
